-- Seed Data: NLP System - COMPREHENSIVE EXTRACTION
-- Sources: 
-- 1. brain_logic/CitizenLink_Simulated_System/data/nlp_dictionaries.json (Version 3.9.3)
-- 2. brain_logic/CitizenLink_Simulated_System/nlp-processor.js (Version 4.0.0)

-- =================================================================
-- 1. NLP CATEGORY CONFIGURATION (Urgency & Hierarchy)
-- TIER 1: Life-Threatening (90-100)
-- TIER 2: High Priority (70-89)
-- TIER 3: Infrastructure (50-69)
-- TIER 4: Quality of Life (30-49)
-- TIER 5: Minor (10-29)
-- =================================================================
INSERT INTO public.nlp_category_config (category, parent_category, urgency_rating) VALUES
-- Public Safety (Tier 1)
('Fire', 'Public Safety', 100),
('Explosion', 'Public Safety', 100),
('Gas Leak', 'Public Safety', 98),
('Building Collapse', 'Public Safety', 98),
('Medical', 'Public Safety', 95),
('Casualty', 'Public Safety', 95),
('Gunshot', 'Public Safety', 95),
('Accident', 'Public Safety', 90),
('Crime', 'Public Safety', 88),
('Assault', 'Public Safety', 88),
('Robbery', 'Public Safety', 85),
('Rescue', 'Public Safety', 98),

-- Environment (Tier 2/3)
('Earthquake', 'Environment', 95),
('Flash Flood', 'Environment', 90),
('Landslide', 'Environment', 88),
('Flooding', 'Environment', 85),
('Flood', 'Environment', 85),
('Evacuation', 'Environment', 85),
('Stranded', 'Environment', 78),

-- Utilities (Tier 3)
('Power Line Down', 'Utilities', 82),
('Transformer Explosion', 'Utilities', 80),
('Blackout', 'Utilities', 75),
('Pipe Leak', 'Utilities', 65),
('No Water', 'Utilities', 60),
('Low Pressure', 'Utilities', 30),

-- Infrastructure (Tier 3)
('Bridge Collapse', 'Infrastructure', 85),
('Fallen Tree', 'Infrastructure', 60),
('Road Obstruction', 'Infrastructure', 58),
('Road Damage', 'Infrastructure', 55),
('Broken Streetlight', 'Infrastructure', 55),
('Clogged Drainage', 'Infrastructure', 55),
('Clogged Canal', 'Infrastructure', 55),
('Pothole', 'Infrastructure', 50),

-- Sanitation (Tier 4)
('Sewage Leak', 'Sanitation', 55),
('Overflowing Trash', 'Sanitation', 45),
('Illegal Dumping', 'Sanitation', 42),
('Trash', 'Sanitation', 40),
('Garbage', 'Sanitation', 40),
('Dead Animal', 'Sanitation', 35),
('Bad Odor', 'Sanitation', 35),

-- Traffic (Tier 4)
('Traffic', 'Traffic Congestion', 45),
('Traffic Congestion', 'Traffic Congestion', 45),
('Vehicle Breakdown', 'Traffic Congestion', 40),

-- Animals & Pests (Tier 4/5)
('Snake Sighting', 'Stray Animals', 55),
('Stray Dog', 'Stray Animals', 45),
('Stray Animal', 'Stray Animals', 40),
('Health Hazard', 'Pest Infestation', 50),
('Mosquito Breeding', 'Pest Infestation', 40),
('Pest Infestation', 'Pest Infestation', 35),

-- Social & Noise (Tier 5)
('Vandalism', 'Public Safety', 35),
('Noise Complaint', 'Noise Complaint', 35),
('Noise', 'Noise Complaint', 35),
('Loud Music', 'Noise Complaint', 30),
('Karaoke', 'Noise Complaint', 30),
('Barking Dog', 'Noise Complaint', 25),
('Loitering', 'Public Safety', 20),
('Others', 'Others', 30)
ON CONFLICT (category) DO UPDATE SET urgency_rating = EXCLUDED.urgency_rating;

-- =================================================================
-- 2. NLP KEYWORDS (Comprehensive from JSON + JS)
-- Includes Tagalog, Bisaya, English variants
-- =================================================================
INSERT INTO public.nlp_keywords (term, category, subcategory, confidence) VALUES

-- === INFRASTRUCTURE: POTHOLE ===
('lubak', 'Infrastructure', 'Pothole', 0.95),
('malubak', 'Infrastructure', 'Pothole', 0.90),
('butas', 'Infrastructure', 'Pothole', 0.85),
('pothole', 'Infrastructure', 'Pothole', 0.95),
('potholes', 'Infrastructure', 'Pothole', 0.95),
('road is uneven', 'Infrastructure', 'Pothole', 0.90),
('uneven road', 'Infrastructure', 'Pothole', 0.90),
('bumpy road', 'Infrastructure', 'Pothole', 0.90),
('rough road', 'Infrastructure', 'Pothole', 0.90),
('rough surface', 'Infrastructure', 'Pothole', 0.85),
('large pothole', 'Infrastructure', 'Pothole', 0.95),
('deep pothole', 'Infrastructure', 'Pothole', 0.95),
('massive pothole', 'Infrastructure', 'Pothole', 0.95),
('huge hole in road', 'Infrastructure', 'Pothole', 0.95),
('dangerous pothole', 'Infrastructure', 'Pothole', 0.95),
('hole in the road', 'Infrastructure', 'Pothole', 0.95),
('butas sa daan', 'Infrastructure', 'Pothole', 0.95),
('may butas ang daan', 'Infrastructure', 'Pothole', 0.95),
('nakita ko may lubak', 'Infrastructure', 'Pothole', 0.90),
('pothole sa gilid ng daan', 'Infrastructure', 'Pothole', 0.95),
('pothole sa daan', 'Infrastructure', 'Pothole', 0.95),
('may pothole', 'Infrastructure', 'Pothole', 0.95),
('nabutas', 'Infrastructure', 'Pothole', 0.90),
('bako', 'Infrastructure', 'Pothole', 0.90),
('bako-bako', 'Infrastructure', 'Pothole', 0.90),
('bakobako', 'Infrastructure', 'Pothole', 0.90),
('bungag', 'Infrastructure', 'Pothole', 0.90),

-- === INFRASTRUCTURE: ROAD DAMAGE ===
('road damage', 'Infrastructure', 'Road Damage', 0.95),
('damaged road', 'Infrastructure', 'Road Damage', 0.95),
('broken road', 'Infrastructure', 'Road Damage', 0.95),
('cracked road', 'Infrastructure', 'Road Damage', 0.90),
('cracked pavement', 'Infrastructure', 'Road Damage', 0.90),
('road cracks', 'Infrastructure', 'Road Damage', 0.90),
('pavement damage', 'Infrastructure', 'Road Damage', 0.90),
('road surface damage', 'Infrastructure', 'Road Damage', 0.90),
('road deterioration', 'Infrastructure', 'Road Damage', 0.90),
('worn out road', 'Infrastructure', 'Road Damage', 0.85),
('damaged asphalt', 'Infrastructure', 'Road Damage', 0.90),
('crumbling road', 'Infrastructure', 'Road Damage', 0.90),
('eroded road', 'Infrastructure', 'Road Damage', 0.85),
('sunken road', 'Infrastructure', 'Road Damage', 0.85),
('depressed pavement', 'Infrastructure', 'Road Damage', 0.85),
('hazardous road', 'Infrastructure', 'Road Damage', 0.90),
('unsafe road conditions', 'Infrastructure', 'Road Damage', 0.90),
('road needs repair', 'Infrastructure', 'Road Damage', 0.90),
('road needs fixing', 'Infrastructure', 'Road Damage', 0.90),
('bad road condition', 'Infrastructure', 'Road Damage', 0.90),
('poor road quality', 'Infrastructure', 'Road Damage', 0.85),
('road maintenance needed', 'Infrastructure', 'Road Damage', 0.85),
('road in bad shape', 'Infrastructure', 'Road Damage', 0.85),
('sira ang daan', 'Infrastructure', 'Road Damage', 0.90),
('bangag diri', 'Infrastructure', 'Road Damage', 0.85),
('guho', 'Infrastructure', 'Road Damage', 0.85),
('naguho', 'Infrastructure', 'Road Damage', 0.90),
('sirang kalsada', 'Infrastructure', 'Road Damage', 0.95),
('wasak ang daan', 'Infrastructure', 'Road Damage', 0.90),
('lubog ang daan', 'Infrastructure', 'Road Damage', 0.85),
('bali-bali ang daan', 'Infrastructure', 'Road Damage', 0.90),
('guba ang dalan', 'Infrastructure', 'Road Damage', 0.90),
('nangabuak', 'Infrastructure', 'Road Damage', 0.85),
('biat', 'Infrastructure', 'Road Damage', 0.85),
('guba nga dalan', 'Infrastructure', 'Road Damage', 0.90),
('naguba', 'Infrastructure', 'Road Damage', 0.90),
('nangaguba', 'Infrastructure', 'Road Damage', 0.90),
('unsafe road', 'Infrastructure', 'Road Damage', 0.90),
('unsafe', 'Infrastructure', 'Road Damage', 0.85),

-- === INFRASTRUCTURE: STREETLIGHT ===
('broken streetlight', 'Infrastructure', 'Broken Streetlight', 0.95),
('streetlight not working', 'Infrastructure', 'Broken Streetlight', 0.95),
('streetlight out', 'Infrastructure', 'Broken Streetlight', 0.90),
('no streetlight', 'Infrastructure', 'Broken Streetlight', 0.90),
('dark street', 'Infrastructure', 'Broken Streetlight', 0.85),
('poor lighting', 'Infrastructure', 'Broken Streetlight', 0.85),
('inadequate lighting', 'Infrastructure', 'Broken Streetlight', 0.85),
('streetlight malfunction', 'Infrastructure', 'Broken Streetlight', 0.90),
('light pole broken', 'Infrastructure', 'Broken Streetlight', 0.90),
('street lamp broken', 'Infrastructure', 'Broken Streetlight', 0.90),
('lights not working', 'Infrastructure', 'Broken Streetlight', 0.90),
('area too dark', 'Infrastructure', 'Broken Streetlight', 0.85),
('needs street lighting', 'Infrastructure', 'Broken Streetlight', 0.85),
('flickering light', 'Infrastructure', 'Broken Streetlight', 0.85),
('sirang street light', 'Infrastructure', 'Broken Streetlight', 0.95),
('hindi umi ilaw', 'Infrastructure', 'Broken Streetlight', 0.85),
('nakita akong sirang street light', 'Infrastructure', 'Broken Streetlight', 0.90),
('walang ilaw', 'Infrastructure', 'Broken Streetlight', 0.90),
('madilim', 'Infrastructure', 'Broken Streetlight', 0.80),
('madilim dito', 'Infrastructure', 'Broken Streetlight', 0.85),
('patay ang ilaw', 'Infrastructure', 'Broken Streetlight', 0.90),
('sira ang poste', 'Infrastructure', 'Broken Streetlight', 0.85),
('busted ang ilaw', 'Infrastructure', 'Broken Streetlight', 0.90),
('kumukurap', 'Infrastructure', 'Broken Streetlight', 0.85),
('paputol-putol ang ilaw', 'Infrastructure', 'Broken Streetlight', 0.85),
('walay suga', 'Infrastructure', 'Broken Streetlight', 0.90),
('ngitngit diri', 'Infrastructure', 'Broken Streetlight', 0.85),
('naponder', 'Infrastructure', 'Broken Streetlight', 0.90),
('nag ponder', 'Infrastructure', 'Broken Streetlight', 0.90),
('ponder', 'Infrastructure', 'Broken Streetlight', 0.85),
('pundido', 'Infrastructure', 'Broken Streetlight', 0.90),
('dilim', 'Infrastructure', 'Broken Streetlight', 0.85),
('ngitngit', 'Infrastructure', 'Broken Streetlight', 0.85),

-- === INFRASTRUCTURE: GENERAL ===
('daan', 'Infrastructure', 'Infrastructure', 0.80),
('kalsada', 'Infrastructure', 'Infrastructure', 0.80),
('daanan', 'Infrastructure', 'Infrastructure', 0.80),
('lansangan', 'Infrastructure', 'Infrastructure', 0.80),
('highway', 'Infrastructure', 'Infrastructure', 0.90),
('national road', 'Infrastructure', 'Infrastructure', 0.90),
('barangay road', 'Infrastructure', 'Infrastructure', 0.85),
('eskinita', 'Infrastructure', 'Infrastructure', 0.80),
('kalye', 'Infrastructure', 'Infrastructure', 0.80),
('overpass', 'Infrastructure', 'Infrastructure', 0.90),
('underpass', 'Infrastructure', 'Infrastructure', 0.90),
('sidewalk', 'Infrastructure', 'Infrastructure', 0.85),
('bangketa', 'Infrastructure', 'Infrastructure', 0.85),
('dalan', 'Infrastructure', 'Infrastructure', 0.80),

-- === INFRASTRUCTURE: BRIDGE ===
('tulay', 'Infrastructure', 'Bridge Collapse', 0.95),
('bridge', 'Infrastructure', 'Bridge Collapse', 0.95),
('sirang tulay', 'Infrastructure', 'Bridge Collapse', 0.95),
('gumuho ang tulay', 'Infrastructure', 'Bridge Collapse', 0.98),
('mapanganib ang tulay', 'Infrastructure', 'Bridge Collapse', 0.90),
('luma na ang tulay', 'Infrastructure', 'Bridge Collapse', 0.80),
('taytay', 'Infrastructure', 'Bridge Collapse', 0.95),
('naguba ang taytay', 'Infrastructure', 'Bridge Collapse', 0.95),
('broken bridge', 'Infrastructure', 'Bridge Collapse', 0.95),
('bridge is collapsing', 'Infrastructure', 'Bridge Collapse', 0.98),

-- === UTILITIES: NO WATER ===
('no water supply', 'Utilities', 'No Water', 0.95),
('water shortage', 'Utilities', 'No Water', 0.95),
('water outage', 'Utilities', 'No Water', 0.95),
('no running water', 'Utilities', 'No Water', 0.95),
('dry tap', 'Utilities', 'No Water', 0.90),
('dry faucet', 'Utilities', 'No Water', 0.90),
('water cut off', 'Utilities', 'No Water', 0.95),
('water service interrupted', 'Utilities', 'No Water', 0.90),
('water supply cut', 'Utilities', 'No Water', 0.95),
('water disruption', 'Utilities', 'No Water', 0.90),
('barely any water', 'Utilities', 'No Water', 0.85),
('walang tubig', 'Utilities', 'No Water', 0.95),
('wala kaming tubig', 'Utilities', 'No Water', 0.95),
('way tubig', 'Utilities', 'No Water', 0.95),
('way tubig skwater', 'Utilities', 'No Water', 0.90),
('nawalan ng tubig', 'Utilities', 'No Water', 0.90),
('once a week lang nagkaka tubig', 'Utilities', 'No Water', 0.90),
('sa gabi lang may tubig', 'Utilities', 'No Water', 0.90),
('palaging nawawala yung tubig', 'Utilities', 'No Water', 0.90),
('di kami makapag laba', 'Utilities', 'No Water', 0.80),
('gusto ko nang maligo', 'Utilities', 'No Water', 0.75),
('di man lang maka inom', 'Utilities', 'No Water', 0.85),
('subrag init', 'Utilities', 'No Water', 0.70),
('putol ang tubig', 'Utilities', 'No Water', 0.95),
('naputol ang tubig', 'Utilities', 'No Water', 0.95),
('wala pa ring tubig', 'Utilities', 'No Water', 0.95),
('ilang araw na walang tubig', 'Utilities', 'No Water', 0.95),
('matagal na walang tubig', 'Utilities', 'No Water', 0.95),
('tubig', 'Utilities', 'No Water', 0.90),
('wala tubig', 'Utilities', 'No Water', 0.95),
('walay tubig', 'Utilities', 'No Water', 0.95),
('nawalan', 'Utilities', 'No Water', 0.85),
('putol tubig', 'Utilities', 'No Water', 0.95),
('naputol ang gripo', 'Utilities', 'No Water', 0.85),
('no water', 'Utilities', 'No Water', 0.95),

-- === UTILITIES: LOW PRESSURE ===
('no water pressure', 'Utilities', 'Low Pressure', 0.90),
('weak water flow', 'Utilities', 'Low Pressure', 0.85),
('low water pressure', 'Utilities', 'Low Pressure', 0.90),
('poor water pressure', 'Utilities', 'Low Pressure', 0.85),
('trickle of water', 'Utilities', 'Low Pressure', 0.85),
('mahina yung tubig', 'Utilities', 'Low Pressure', 0.85),
('mahina yung tubig sa umaga', 'Utilities', 'Low Pressure', 0.90),
('low pressure', 'Utilities', 'Low Pressure', 0.90),
('mahina', 'Utilities', 'Low Pressure', 0.85),
('mahinang tubig', 'Utilities', 'Low Pressure', 0.85),
('weak water', 'Utilities', 'Low Pressure', 0.90),

-- === UTILITIES: PIPE LEAK ===
('water leak', 'Utilities', 'Pipe Leak', 0.90),
('leaking pipe', 'Utilities', 'Pipe Leak', 0.90),
('burst pipe', 'Utilities', 'Pipe Leak', 0.95),
('broken pipe', 'Utilities', 'Pipe Leak', 0.95),
('pipe rupture', 'Utilities', 'Pipe Leak', 0.95),
('water main break', 'Utilities', 'Pipe Leak', 0.95),
('tumatagos ang tubig', 'Utilities', 'Pipe Leak', 0.90),
('may tulo sa tubo', 'Utilities', 'Pipe Leak', 0.90),
('pumutok ang tubo', 'Utilities', 'Pipe Leak', 0.95),
('butas ang tubo', 'Utilities', 'Pipe Leak', 0.90),

-- === UTILITIES: BLACKOUT ===
('power outage', 'Utilities', 'Blackout', 0.95),
('no power', 'Utilities', 'Blackout', 0.95),
('no electricity', 'Utilities', 'Blackout', 0.95),
('power cut', 'Utilities', 'Blackout', 0.95),
('electricity cut', 'Utilities', 'Blackout', 0.95),
('power failure', 'Utilities', 'Blackout', 0.95),
('electrical outage', 'Utilities', 'Blackout', 0.95),
('lights out', 'Utilities', 'Blackout', 0.90),
('lost power', 'Utilities', 'Blackout', 0.90),
('power interruption', 'Utilities', 'Blackout', 0.95),
('electrical problem', 'Utilities', 'Blackout', 0.85),
('brownout', 'Utilities', 'Blackout', 0.95),
('walang kuryente', 'Utilities', 'Blackout', 0.95),
('nawalan ng ilaw', 'Utilities', 'Blackout', 0.90),
('blackout', 'Utilities', 'Blackout', 0.95),
('naputol ang kuryente', 'Utilities', 'Blackout', 0.95),
('rotating brownout', 'Utilities', 'Blackout', 0.90),
('scheduled brownout', 'Utilities', 'Blackout', 0.85),
('walay kuryente', 'Utilities', 'Blackout', 0.95),
('namatay ang kuryente', 'Utilities', 'Blackout', 0.90),
('kuryente', 'Utilities', 'Blackout', 0.90),
('wala kuryente', 'Utilities', 'Blackout', 0.95),
('brown out', 'Utilities', 'Blackout', 0.95),
('black out', 'Utilities', 'Blackout', 0.95),

-- === UTILITIES: POWER LINE / TRANSFORMER ===
('transformer issue', 'Utilities', 'Transformer Explosion', 0.90),
('power line down', 'Utilities', 'Power Line Down', 0.95),
('electrical line down', 'Utilities', 'Power Line Down', 0.95),
('sparking wires', 'Utilities', 'Power Line Down', 0.90),
('exposed wires', 'Utilities', 'Power Line Down', 0.90),
('dangerous wires', 'Utilities', 'Power Line Down', 0.90),
('nahulog ang linya', 'Utilities', 'Power Line Down', 0.90),
('naputol ang kawad', 'Utilities', 'Power Line Down', 0.90),
('sumabog ang transformer', 'Utilities', 'Transformer Explosion', 0.95),
('sparking', 'Utilities', 'Power Line Down', 0.85),
('chicharon', 'Utilities', 'Transformer Explosion', 0.80),

-- === SANITATION: TRASH ===
('trash', 'Sanitation', 'Trash', 0.95),
('garbage', 'Sanitation', 'Trash', 0.95),
('waste', 'Sanitation', 'Trash', 0.90),
('litter', 'Sanitation', 'Trash', 0.90),
('rubbish', 'Sanitation', 'Trash', 0.90),
('uncollected garbage', 'Sanitation', 'Trash', 0.95),
('trash not collected', 'Sanitation', 'Trash', 0.95),
('garbage scattered', 'Sanitation', 'Trash', 0.90),
('rotting trash', 'Sanitation', 'Trash', 0.90),
('unsanitary conditions', 'Sanitation', 'Trash', 0.90),
('health hazard', 'Sanitation', 'Trash', 0.90),
('basura', 'Sanitation', 'Trash', 0.95),
('basura sa daan', 'Sanitation', 'Trash', 0.95),
('wla bang lilinis', 'Sanitation', 'Trash', 0.85),
('di nakuha ang basura', 'Sanitation', 'Trash', 0.90),
('di nakuha ang basura ng maayos', 'Sanitation', 'Trash', 0.90),
('di madaanan', 'Sanitation', 'Trash', 0.80),
('pati sa sidewalk', 'Sanitation', 'Trash', 0.70),
('hindi dinadaan ng truck', 'Sanitation', 'Trash', 0.90),
('basurero', 'Sanitation', 'Trash', 0.70),
('garbage truck', 'Sanitation', 'Trash', 0.80),
('hugaw', 'Sanitation', 'Trash', 0.85),
('basura sa kadalanan', 'Sanitation', 'Trash', 0.90),
('nabulok', 'Sanitation', 'Trash', 0.85),
('bulok na basura', 'Sanitation', 'Trash', 0.90),
('kalat', 'Sanitation', 'Trash', 0.90),
('makalat', 'Sanitation', 'Trash', 0.90),
('dumi', 'Sanitation', 'Trash', 0.90),
('marumi', 'Sanitation', 'Trash', 0.90),
('hindi nakuha', 'Sanitation', 'Trash', 0.90),
('di kinolekta', 'Sanitation', 'Trash', 0.90),
('uncollected waste', 'Sanitation', 'Trash', 0.95),

-- === SANITATION: OVERFLOWING ===
('trash pile', 'Sanitation', 'Overflowing Trash', 0.95),
('garbage pile', 'Sanitation', 'Overflowing Trash', 0.95),
('overflowing trash', 'Sanitation', 'Overflowing Trash', 0.95),
('trash bin full', 'Sanitation', 'Overflowing Trash', 0.90),
('dumpster overflowing', 'Sanitation', 'Overflowing Trash', 0.90),
('trash everywhere', 'Sanitation', 'Overflowing Trash', 0.95),
('daming basura', 'Sanitation', 'Overflowing Trash', 0.95),
('marami basura', 'Sanitation', 'Overflowing Trash', 0.90),
('tambak na yung basura', 'Sanitation', 'Overflowing Trash', 0.90),
('may umaapaw na basura', 'Sanitation', 'Overflowing Trash', 0.95),
('tambak', 'Sanitation', 'Overflowing Trash', 0.90),
('nakatambak', 'Sanitation', 'Overflowing Trash', 0.90),
('puno ng basura', 'Sanitation', 'Overflowing Trash', 0.90),

-- === SANITATION: ILLEGAL DUMPING ===
('littering', 'Sanitation', 'Illegal Dumping', 0.90),
('illegal dumping', 'Sanitation', 'Illegal Dumping', 0.95),
('waste dumping', 'Sanitation', 'Illegal Dumping', 0.95),
('tapon ng basura', 'Sanitation', 'Illegal Dumping', 0.90),
('nagtatapon ng basura', 'Sanitation', 'Illegal Dumping', 0.90),
('tapunan ng basura', 'Sanitation', 'Illegal Dumping', 0.85),
('dumping', 'Sanitation', 'Illegal Dumping', 0.90),

-- === SANITATION: ODOR ===
('smelly garbage', 'Sanitation', 'Bad Odor', 0.90),
('garbage odor', 'Sanitation', 'Bad Odor', 0.90),
('trash smell', 'Sanitation', 'Bad Odor', 0.90),
('baho', 'Sanitation', 'Bad Odor', 0.95),
('ambaho', 'Sanitation', 'Bad Odor', 0.95),
('napaka baho', 'Sanitation', 'Bad Odor', 0.95),
('sobrang baho', 'Sanitation', 'Bad Odor', 0.95),
('ang sakita sa mata tingnan', 'Sanitation', 'Bad Odor', 0.80),
('mabaho', 'Sanitation', 'Bad Odor', 0.95),
('nangangamoy', 'Sanitation', 'Bad Odor', 0.90),
('amoy patay', 'Sanitation', 'Dead Animal', 0.90),
('amoy bulok', 'Sanitation', 'Bad Odor', 0.90),
('amoy dumi', 'Sanitation', 'Bad Odor', 0.90),
('nakakasuya ang amoy', 'Sanitation', 'Bad Odor', 0.85),
('nakakahilo ang amoy', 'Sanitation', 'Bad Odor', 0.85),
('baho kaayo', 'Sanitation', 'Bad Odor', 0.95),
('makabaw', 'Sanitation', 'Bad Odor', 0.90),
('amoy', 'Sanitation', 'Bad Odor', 0.85),
('maamoy', 'Sanitation', 'Bad Odor', 0.85),
('maasim', 'Sanitation', 'Bad Odor', 0.85),
('mabahong basura', 'Sanitation', 'Bad Odor', 0.95),
('stink', 'Sanitation', 'Bad Odor', 0.90),
('stench', 'Sanitation', 'Bad Odor', 0.90),
('smelly', 'Sanitation', 'Bad Odor', 0.90),

-- === SANITATION: DRAINAGE ===
('nagbara yung drainage', 'Infrastructure', 'Clogged Drainage', 0.95),
('barado', 'Infrastructure', 'Clogged Drainage', 0.90),
('wla na madaanan yung tubig', 'Infrastructure', 'Clogged Drainage', 0.90),
('baradong canal', 'Infrastructure', 'Clogged Canal', 0.95),
('baradong imburnal', 'Infrastructure', 'Clogged Drainage', 0.95),
('umaapaw ang canal', 'Infrastructure', 'Clogged Canal', 0.90),
('puno na ang drainage', 'Infrastructure', 'Clogged Drainage', 0.90),
('di makalusot ang tubig', 'Infrastructure', 'Clogged Drainage', 0.90),
('septic tank', 'Sanitation', 'Sewage Leak', 0.80),
('umaapaw ang septic', 'Sanitation', 'Sewage Leak', 0.95),
('tumatae sa labas', 'Sanitation', 'Sewage Leak', 0.90),
('nabasag ang imburnal', 'Infrastructure', 'Clogged Drainage', 0.85),
('barado ang imburnal', 'Infrastructure', 'Clogged Drainage', 0.95),
('puno sa basura ang kanal', 'Infrastructure', 'Clogged Canal', 0.90),
('dili na makadagan ang tubig', 'Infrastructure', 'Clogged Drainage', 0.90),
('walay dalanan ang tubig', 'Infrastructure', 'Clogged Drainage', 0.90),
('nagsapot na ang kanal', 'Infrastructure', 'Clogged Drainage', 0.90),
('daghan basura sa kanal', 'Infrastructure', 'Clogged Drainage', 0.90),
('gamay ra ang agianan sa tubig', 'Infrastructure', 'Clogged Drainage', 0.85),
('mabaw ra ang imburnal', 'Infrastructure', 'Clogged Drainage', 0.85),

-- === ENVIRONMENT: FLOOD ===
('baha', 'Environment', 'Flood', 0.95),
('flooded', 'Environment', 'Flood', 0.95),
('flooding', 'Environment', 'Flood', 0.95),
('underwater', 'Environment', 'Flood', 0.95),
('submerged', 'Environment', 'Flood', 0.95),
('water level rising', 'Environment', 'Flood', 0.95),
('rising water', 'Environment', 'Flood', 0.95),
('flood water', 'Environment', 'Flood', 0.95),
('knee deep', 'Environment', 'Flood', 0.90),
('waist deep', 'Environment', 'Flood', 0.95),
('chest deep', 'Environment', 'Flood', 0.98),
('neck deep', 'Environment', 'Flood', 0.98),
('flash flood', 'Environment', 'Flash Flood', 0.98),
('river overflow', 'Environment', 'Flood', 0.95),
('overflowing', 'Environment', 'Flood', 0.90),
('impassable', 'Environment', 'Flood', 0.90),
('cant cross', 'Environment', 'Flood', 0.85),
('water entering', 'Environment', 'Flood', 0.90),
('house flooded', 'Environment', 'Flood', 0.95),
('street flooded', 'Environment', 'Flood', 0.95),
('road flooded', 'Environment', 'Flood', 0.95),
('bumaha', 'Environment', 'Flood', 0.95),
('bumaha dito', 'Environment', 'Flood', 0.95),
('mataas ang baha', 'Environment', 'Flood', 0.95),
('malalim na ang baha', 'Environment', 'Flood', 0.95),
('ang lalim nang baha', 'Environment', 'Flood', 0.95),
('abot tuhod', 'Environment', 'Flood', 0.90),
('abot tuhod na', 'Environment', 'Flood', 0.90),
('abot bewang', 'Environment', 'Flood', 0.95),
('abot leeg', 'Environment', 'Flood', 0.98),
('pumapasok na sa bahay', 'Environment', 'Flood', 0.90),
('baha walang tulay', 'Environment', 'Flood', 0.85),
('may dalang kahoy yung baha', 'Environment', 'Flood', 0.85),
('umaapaw ang ilog', 'Environment', 'Flood', 0.95),
('lumubog', 'Environment', 'Flood', 0.90),
('hindi na makatawid', 'Environment', 'Flood', 0.85),
('stranded', 'Environment', 'Stranded', 0.90),
('nastranded', 'Environment', 'Stranded', 0.90),
('hindi makauwi', 'Environment', 'Stranded', 0.85),
('binaha ang bahay', 'Environment', 'Flood', 0.95),
('binaha', 'Environment', 'Flood', 0.95),
('tubig baha', 'Environment', 'Flood', 0.90),
('nagbaha', 'Environment', 'Flood', 0.95),
('baha kaayo', 'Environment', 'Flood', 0.95),
('lunop', 'Environment', 'Flood', 0.90),
('permi lunop', 'Environment', 'Flood', 0.90),
('permi gyud lunop', 'Environment', 'Flood', 0.90),
('nag lunop', 'Environment', 'Flood', 0.95),
('mag lunop dayon', 'Environment', 'Flood', 0.85),
('taas kaayo ang tubig', 'Environment', 'Flood', 0.90),
('pag ulan kusog', 'Environment', 'Flood', 0.80),
('mag overflow', 'Environment', 'Flood', 0.85),
('nagtubig', 'Environment', 'Flood', 0.85),
('bumabaha', 'Environment', 'Flood', 0.95),
('bahain', 'Environment', 'Flood', 0.90),
('taas ng tubig', 'Environment', 'Flood', 0.90),
('mataas ang tubig', 'Environment', 'Flood', 0.90),
('tubig sa kalsada', 'Environment', 'Flood', 0.90),
('lunod', 'Environment', 'Flood', 0.90),
('nalulunod', 'Environment', 'Flood', 0.95),
('nalunop', 'Environment', 'Flood', 0.95),
('gilunop', 'Environment', 'Flood', 0.95),
('apaw', 'Environment', 'Flood', 0.90),
('miapaw', 'Environment', 'Flood', 0.90),
('nag-apaw', 'Environment', 'Flood', 0.90),
('nagaapaw', 'Environment', 'Flood', 0.90),
('grabe ang baha', 'Environment', 'Flood', 0.95),
('overflow', 'Environment', 'Flood', 0.90),
('water level', 'Environment', 'Flood', 0.85),

-- === ENVIRONMENT: LANDSLIDE & TREE ===
('landslide', 'Environment', 'Landslide', 0.95),
('gumuho', 'Environment', 'Landslide', 0.90),
('pagguho ng lupa', 'Environment', 'Landslide', 0.95),
('natabunan', 'Environment', 'Landslide', 0.90),
('erosion', 'Environment', 'Landslide', 0.85),
('nagkalandslide', 'Environment', 'Landslide', 0.95),
('bumagsak na puno', 'Infrastructure', 'Fallen Tree', 0.95),
('nabuwal na puno', 'Infrastructure', 'Fallen Tree', 0.95),
('puno sa daan', 'Infrastructure', 'Fallen Tree', 0.90),
('tumumbang puno', 'Infrastructure', 'Fallen Tree', 0.95),
('nabali ang puno', 'Infrastructure', 'Fallen Tree', 0.85),
('harang ang puno', 'Infrastructure', 'Road Obstruction', 0.90),

-- === PUBLIC SAFETY: FIRE ===
('sunog', 'Public Safety', 'Fire', 0.98),
('nasusunog', 'Public Safety', 'Fire', 0.98),
('may sunog', 'Public Safety', 'Fire', 0.98),
('nasunog', 'Public Safety', 'Fire', 0.95),
('fire', 'Public Safety', 'Fire', 0.98),
('house fire', 'Public Safety', 'Fire', 0.98),
('building fire', 'Public Safety', 'Fire', 0.98),
('burning', 'Public Safety', 'Fire', 0.95),
('on fire', 'Public Safety', 'Fire', 0.98),
('flames', 'Public Safety', 'Fire', 0.95),
('blaze', 'Public Safety', 'Fire', 0.95),
('blazing', 'Public Safety', 'Fire', 0.95),
('inferno', 'Public Safety', 'Fire', 0.95),
('wildfire', 'Public Safety', 'Fire', 0.95),
('grass fire', 'Public Safety', 'Fire', 0.95),
('forest fire', 'Public Safety', 'Fire', 0.95),
('electrical fire', 'Public Safety', 'Fire', 0.98),
('caught fire', 'Public Safety', 'Fire', 0.98),
('fire broke out', 'Public Safety', 'Fire', 0.98),
('fire spreading', 'Public Safety', 'Fire', 0.98),
('smoke coming', 'Public Safety', 'Smoke', 0.90),
('black smoke', 'Public Safety', 'Smoke', 0.90),
('thick smoke', 'Public Safety', 'Smoke', 0.90),
('smoke alarm', 'Public Safety', 'Fire', 0.85),
('fire alarm', 'Public Safety', 'Fire', 0.85),
('engulfed', 'Public Safety', 'Fire', 0.95),
('burn down', 'Public Safety', 'Fire', 0.95),
('burned down', 'Public Safety', 'Fire', 0.95),
('usok', 'Public Safety', 'Smoke', 0.85),
('maraming usok', 'Public Safety', 'Smoke', 0.90),
('maitim na usok', 'Public Safety', 'Smoke', 0.90),
('nagsisimula na ang apoy', 'Public Safety', 'Fire', 0.95),
('kumakalat ang apoy', 'Public Safety', 'Fire', 0.98),
('apoy', 'Public Safety', 'Fire', 0.90),
('nagliliyab', 'Public Safety', 'Fire', 0.95),
('kayo', 'Public Safety', 'Fire', 0.95),
('nagkayo', 'Public Safety', 'Fire', 0.95),
('nasunog ang balay', 'Public Safety', 'Fire', 0.98),

-- === PUBLIC SAFETY: CRIME/ACCIDENT ===
('aksidente', 'Public Safety', 'Accident', 0.95),
('crash', 'Public Safety', 'Accident', 0.95),
('crashed', 'Public Safety', 'Accident', 0.95),
('collision', 'Public Safety', 'Accident', 0.95),
('collided', 'Public Safety', 'Accident', 0.95),
('hit and run', 'Public Safety', 'Accident', 0.98),
('got hit', 'Public Safety', 'Accident', 0.95),
('run over', 'Public Safety', 'Accident', 0.98),
('ran over', 'Public Safety', 'Accident', 0.98),
('overturned', 'Public Safety', 'Accident', 0.95),
('flipped over', 'Public Safety', 'Accident', 0.95),
('motorcycle accident', 'Public Safety', 'Accident', 0.95),
('truck accident', 'Public Safety', 'Accident', 0.95),
('bus accident', 'Public Safety', 'Accident', 0.95),
('traffic accident', 'Public Safety', 'Accident', 0.95),
('road accident', 'Public Safety', 'Accident', 0.95),
('pedestrian hit', 'Public Safety', 'Accident', 0.98),
('nagkaaksidente', 'Public Safety', 'Accident', 0.95),
('nabangga', 'Public Safety', 'Accident', 0.95),
('nagbangga', 'Public Safety', 'Accident', 0.95),
('nagkabangaan', 'Public Safety', 'Accident', 0.95),
('nasagasaan', 'Public Safety', 'Accident', 0.98),
('vehicular accident', 'Public Safety', 'Accident', 0.95),
('car accident', 'Public Safety', 'Accident', 0.95),
('motor accident', 'Public Safety', 'Accident', 0.95),
('nadisgrasya', 'Public Safety', 'Accident', 0.90),
('sumalpok', 'Public Safety', 'Accident', 0.90),
('tumilapon', 'Public Safety', 'Accident', 0.85),
('nadulas', 'Public Safety', 'Accident', 0.80),
('naaksidente', 'Public Safety', 'Accident', 0.95),
('carambola', 'Public Safety', 'Accident', 0.95),
('krimen', 'Public Safety', 'Crime', 0.95),
('holdap', 'Public Safety', 'Crime', 0.95),
('nakawan', 'Public Safety', 'Crime', 0.95),
('magnanakaw', 'Public Safety', 'Crime', 0.95),
('away', 'Public Safety', 'Crime', 0.85),
('saksak', 'Public Safety', 'Crime', 0.95),
('barilan', 'Public Safety', 'Crime', 0.98),
('putukan', 'Public Safety', 'Crime', 0.98),
('patay', 'Public Safety', 'Medical', 0.95),
('namatay', 'Public Safety', 'Medical', 0.95),
('bangkay', 'Public Safety', 'Medical', 0.95),
('sugatan', 'Public Safety', 'Medical', 0.95),
('crime', 'Public Safety', 'Crime', 0.95),
('robbery', 'Public Safety', 'Crime', 0.95),
('assault', 'Public Safety', 'Crime', 0.95),
('emergency', 'Public Safety', 'Medical', 0.95),
('danger', 'Public Safety', 'Others', 0.80),
('dangerous', 'Public Safety', 'Others', 0.80),
('drugs', 'Public Safety', 'Drug Activity', 0.90),
('drug dealing', 'Public Safety', 'Drug Activity', 0.95),
('nanakawan', 'Public Safety', 'Crime', 0.95),
('may magnanakaw', 'Public Safety', 'Crime', 0.95),
('holdup', 'Public Safety', 'Crime', 0.98),
('holdaper', 'Public Safety', 'Crime', 0.95),
('snatcher', 'Public Safety', 'Crime', 0.95),
('nasnatcher', 'Public Safety', 'Crime', 0.95),
('riot', 'Public Safety', 'Crime', 0.95),
('nagkaaway', 'Public Safety', 'Crime', 0.85),
('sinaksak', 'Public Safety', 'Crime', 0.98),
('binaril', 'Public Safety', 'Crime', 0.98),
('may baril', 'Public Safety', 'Crime', 0.95),
('droga', 'Public Safety', 'Drug Activity', 0.90),
('vandalism', 'Public Safety', 'Vandalism', 0.85),
('pinandalize', 'Public Safety', 'Vandalism', 0.85),
('kawatan', 'Public Safety', 'Crime', 0.95),
('tulisan', 'Public Safety', 'Crime', 0.95),

-- === PUBLIC SAFETY: MEDICAL ===
('medical emergency', 'Public Safety', 'Medical', 0.98),
('injured', 'Public Safety', 'Medical', 0.95),
('injuries', 'Public Safety', 'Medical', 0.95),
('wounded', 'Public Safety', 'Medical', 0.95),
('bleeding', 'Public Safety', 'Medical', 0.95),
('unconscious', 'Public Safety', 'Medical', 0.98),
('not breathing', 'Public Safety', 'Medical', 0.98),
('stopped breathing', 'Public Safety', 'Medical', 0.98),
('fainted', 'Public Safety', 'Medical', 0.90),
('passed out', 'Public Safety', 'Medical', 0.90),
('collapsed', 'Public Safety', 'Medical', 0.95),
('seizure', 'Public Safety', 'Medical', 0.98),
('choking', 'Public Safety', 'Medical', 0.98),
('chest pain', 'Public Safety', 'Medical', 0.95),
('difficulty breathing', 'Public Safety', 'Medical', 0.95),
('cant breathe', 'Public Safety', 'Medical', 0.98),
('allergic reaction', 'Public Safety', 'Medical', 0.95),
('overdose', 'Public Safety', 'Medical', 0.98),
('ambulance', 'Public Safety', 'Medical', 0.90),
('paramedic', 'Public Safety', 'Medical', 0.90),
('CPR', 'Public Safety', 'Medical', 0.95),
('need help', 'Public Safety', 'Medical', 0.85),
('need medical', 'Public Safety', 'Medical', 0.95),
('may sugatan', 'Public Safety', 'Medical', 0.95),
('nasugatan', 'Public Safety', 'Medical', 0.95),
('dumudugo', 'Public Safety', 'Medical', 0.95),
('nawalan ng malay', 'Public Safety', 'Medical', 0.98),
('hinimatay', 'Public Safety', 'Medical', 0.90),
('heart attack', 'Public Safety', 'Medical', 0.98),
('atake sa puso', 'Public Safety', 'Medical', 0.98),
('stroke', 'Public Safety', 'Medical', 0.98),
('ambulansya', 'Public Safety', 'Medical', 0.90),
('ospital', 'Public Safety', 'Medical', 0.80),
('kailangan ng tulong medikal', 'Public Safety', 'Medical', 0.95),
('evacuate', 'Environment', 'Evacuation', 0.95),
('evacuation', 'Environment', 'Evacuation', 0.95),
('lumikas', 'Environment', 'Evacuation', 0.95),
('likas na', 'Environment', 'Evacuation', 0.95),
('evacuees', 'Environment', 'Evacuation', 0.90),
('evacuation center', 'Environment', 'Evacuation', 0.90),
('kailangan ng rescue', 'Public Safety', 'Rescue', 0.98),
('rescue', 'Public Safety', 'Rescue', 0.98),
('trapped', 'Public Safety', 'Rescue', 0.95),
('naiipit', 'Public Safety', 'Rescue', 0.95),

-- === TRAFFIC ===
('trapik', 'Traffic Congestion', 'Traffic', 0.95),
('traffic', 'Traffic Congestion', 'Traffic', 0.95),
('siksikan', 'Traffic Congestion', 'Traffic', 0.90),
('congestion', 'Traffic Congestion', 'Traffic', 0.95),
('hindi makalusot', 'Traffic Congestion', 'Traffic', 0.90),
('di makalusot', 'Traffic Congestion', 'Traffic', 0.90),
('stuck', 'Traffic Congestion', 'Traffic', 0.85),
('mabagal', 'Traffic Congestion', 'Traffic', 0.85),
('matraffic', 'Traffic Congestion', 'Traffic', 0.90),
('matrapik', 'Traffic Congestion', 'Traffic', 0.90),
('bottleneck', 'Traffic Congestion', 'Traffic', 0.90),
('gridlock', 'Traffic Congestion', 'Traffic', 0.95),
('jam', 'Traffic Congestion', 'Traffic', 0.90),
('tumatraffic', 'Traffic Congestion', 'Traffic', 0.90),
('di maka daan', 'Traffic Congestion', 'Traffic', 0.90),
('di ako maka daan', 'Traffic Congestion', 'Traffic', 0.90),
('di na maka daan', 'Traffic Congestion', 'Traffic', 0.90),
('hirap maka daan', 'Traffic Congestion', 'Traffic', 0.90),
('nakakasagabal', 'Infrastructure', 'Road Obstruction', 0.90),
('naka sagabal sa daan', 'Infrastructure', 'Road Obstruction', 0.90),
('traffic jam', 'Traffic Congestion', 'Traffic', 0.95),
('bumubuntot na sasakyan', 'Traffic Congestion', 'Traffic', 0.85),
('masikip ang daan', 'Traffic Congestion', 'Traffic', 0.85),
('harang sa daan', 'Infrastructure', 'Road Obstruction', 0.90),
('road closure', 'Infrastructure', 'Road Obstruction', 0.90),
('sarado ang daan', 'Infrastructure', 'Road Obstruction', 0.90),
('nasira ang kotse', 'Traffic Congestion', 'Vehicle Breakdown', 0.90),
('namatay ang makina', 'Traffic Congestion', 'Vehicle Breakdown', 0.90),
('breakdown', 'Traffic Congestion', 'Vehicle Breakdown', 0.90),
('flat tire', 'Traffic Congestion', 'Vehicle Breakdown', 0.85),
('naflat', 'Traffic Congestion', 'Vehicle Breakdown', 0.85),
('overheating', 'Traffic Congestion', 'Vehicle Breakdown', 0.85),

-- === ANIMALS & PESTS ===
('aso', 'Stray Animals', 'Stray Dog', 0.90),
('gala', 'Stray Animals', 'Stray Dog', 0.85),
('asong gala', 'Stray Animals', 'Stray Dog', 0.95),
('stray dog', 'Stray Animals', 'Stray Dog', 0.95),
('hayop', 'Stray Animals', 'Stray Animal', 0.80),
('ligaw na hayop', 'Stray Animals', 'Stray Animal', 0.90),
('stray animal', 'Stray Animals', 'Stray Animal', 0.95),
('ahas', 'Stray Animals', 'Snake Sighting', 0.95),
('snake', 'Stray Animals', 'Snake Sighting', 0.95),
('iro', 'Stray Animals', 'Stray Dog', 0.90),
('irong buang', 'Stray Animals', 'Stray Dog', 0.90),
('rabid', 'Stray Animals', 'Stray Dog', 0.98),
('loko', 'Stray Animals', 'Stray Dog', 0.85),
('mabangis', 'Stray Animals', 'Stray Dog', 0.90),
('nakita ko ang aso', 'Stray Animals', 'Stray Dog', 0.85),
('nakita akong aso sa daan', 'Stray Animals', 'Stray Dog', 0.90),
('kinagat ako ng aso', 'Stray Animals', 'Stray Dog', 0.95),
('rabid dog', 'Stray Animals', 'Stray Dog', 0.98),
('may rabies', 'Stray Animals', 'Stray Dog', 0.98),
('nagbabangis', 'Stray Animals', 'Stray Dog', 0.90),
('nagwawala ang aso', 'Stray Animals', 'Stray Dog', 0.90),
('halas', 'Stray Animals', 'Snake Sighting', 0.90),
('may ahas', 'Stray Animals', 'Snake Sighting', 0.95),
('bitin', 'Stray Animals', 'Snake Sighting', 0.90),
('patay na hayop', 'Sanitation', 'Dead Animal', 0.90),
('bangkay ng aso', 'Sanitation', 'Dead Animal', 0.95),
('lamok', 'Pest Infestation', 'Mosquito Breeding', 0.90),
('mosquito', 'Pest Infestation', 'Mosquito Breeding', 0.90),
('dengue', 'Pest Infestation', 'Mosquito Breeding', 0.95),
('breeding', 'Pest Infestation', 'Mosquito Breeding', 0.90),
('daga', 'Pest Infestation', 'Pest Infestation', 0.95),
('rats', 'Pest Infestation', 'Pest Infestation', 0.95),
('mice', 'Pest Infestation', 'Pest Infestation', 0.95),
('ipis', 'Pest Infestation', 'Pest Infestation', 0.90),
('cockroach', 'Pest Infestation', 'Pest Infestation', 0.90),
('peste', 'Pest Infestation', 'Pest Infestation', 0.90),
('infestation', 'Pest Infestation', 'Pest Infestation', 0.95),
('kuto', 'Pest Infestation', 'Pest Infestation', 0.85),
('insekto', 'Pest Infestation', 'Pest Infestation', 0.80),
('daga everywhere', 'Pest Infestation', 'Pest Infestation', 0.95),
('pinapasukan na', 'Pest Infestation', 'Pest Infestation', 0.80),
('langgam', 'Pest Infestation', 'Pest Infestation', 0.80),
('daming lamok', 'Pest Infestation', 'Mosquito Breeding', 0.95),
('breeding ground ng lamok', 'Pest Infestation', 'Mosquito Breeding', 0.95),
('may dengue sa area', 'Pest Infestation', 'Mosquito Breeding', 0.95),
('ilaga', 'Pest Infestation', 'Pest Infestation', 0.90),
('uk-uk', 'Pest Infestation', 'Pest Infestation', 0.85),

-- === NOISE ===
('ingay', 'Noise Complaint', 'Noise', 0.90),
('maingay', 'Noise Complaint', 'Noise', 0.95),
('noise', 'Noise Complaint', 'Noise', 0.95),
('noisy', 'Noise Complaint', 'Noise', 0.95),
('karaoke', 'Noise Complaint', 'Noise', 0.85),
('videoke', 'Noise Complaint', 'Noise', 0.85),
('loud music', 'Noise Complaint', 'Noise', 0.90),
('sigaw', 'Noise Complaint', 'Noise', 0.80),
('tahol', 'Noise Complaint', 'Noise', 0.80),
('barking dog', 'Noise Complaint', 'Noise', 0.85),
('construction noise', 'Noise Complaint', 'Noise', 0.90),
('maingay na konstruksyon', 'Noise Complaint', 'Noise', 0.90),
('ang ingay', 'Noise Complaint', 'Noise', 0.95),
('ang iingay', 'Noise Complaint', 'Noise', 0.95),
('sobrang ingay', 'Noise Complaint', 'Noise', 0.95),
('sobrang ingay ng karaoke', 'Noise Complaint', 'Noise', 0.90),
('noise disturbance', 'Noise Complaint', 'Noise', 0.95),
('ingay ng kapitbahay', 'Noise Complaint', 'Noise', 0.90),
('tahol ng aso', 'Noise Complaint', 'Noise', 0.85),
('music', 'Noise Complaint', 'Noise', 0.70),
('party', 'Noise Complaint', 'Noise', 0.70),
('iistorbo', 'Noise Complaint', 'Noise', 0.85),
('kasaba', 'Noise Complaint', 'Noise', 0.90),

-- === ENGLISH & CRITICAL VARIANTS (From JSON lines 1156+) ===
('stink', 'Sanitation', 'Bad Odor', 0.85),
('stench', 'Sanitation', 'Bad Odor', 0.85),
('smelly', 'Sanitation', 'Bad Odor', 0.85),
('foul odor', 'Sanitation', 'Bad Odor', 0.90),
('clogged drain', 'Infrastructure', 'Clogged Drainage', 0.95),
('blocked drainage', 'Infrastructure', 'Clogged Drainage', 0.95),
('lamp post', 'Infrastructure', 'Broken Streetlight', 0.85),
('street light', 'Infrastructure', 'Broken Streetlight', 0.90),
('pavement damage', 'Infrastructure', 'Road Damage', 0.90),
('water outage', 'Utilities', 'No Water', 0.95),
('weak water', 'Utilities', 'Low Pressure', 0.85),
('no electricity', 'Utilities', 'Blackout', 0.95),
('road obstruction', 'Infrastructure', 'Road Obstruction', 0.95),
('blocked road', 'Infrastructure', 'Road Obstruction', 0.90),
('obstruction', 'Infrastructure', 'Road Obstruction', 0.80),
('blockage', 'Infrastructure', 'Road Obstruction', 0.85),
('extreme danger', 'Public Safety', 'Fire', 0.95),
('loud noise', 'Noise Complaint', 'Noise', 0.85),
('road is uneven', 'Infrastructure', 'Road Damage', 0.95),
('road is rough', 'Infrastructure', 'Road Damage', 0.95),
('road is broken', 'Infrastructure', 'Road Damage', 0.95),
('road is damaged', 'Infrastructure', 'Road Damage', 0.95),
('water interruption', 'Utilities', 'No Water', 0.95),
('ran out of water', 'Utilities', 'No Water', 0.95),
('out of water', 'Utilities', 'No Water', 0.95),
('poor sanitation', 'Sanitation', 'Trash', 0.90),
('poor disposal', 'Sanitation', 'Trash', 0.90),
('no proper disposal', 'Sanitation', 'Trash', 0.90),
('pile of trash', 'Sanitation', 'Trash', 0.95),
('a lot of trash', 'Sanitation', 'Trash', 0.95),
('lot of waste', 'Sanitation', 'Trash', 0.90),
('drains are clogged', 'Infrastructure', 'Clogged Drainage', 0.95),
('drain is clogged', 'Infrastructure', 'Clogged Drainage', 0.95),
('drainage problems', 'Infrastructure', 'Clogged Drainage', 0.90),
('poor drainage', 'Infrastructure', 'Clogged Drainage', 0.90),
('no drainage', 'Infrastructure', 'Clogged Drainage', 0.90),
('flood prone', 'Environment', 'Flooding', 0.90),
('flood area', 'Environment', 'Flooding', 0.90),
('flooded area', 'Environment', 'Flooding', 0.95),
('flooding area', 'Environment', 'Flooding', 0.95),
('flood issues', 'Environment', 'Flooding', 0.90),
('flood problems', 'Environment', 'Flooding', 0.90),
('flooding problems', 'Environment', 'Flooding', 0.90),
('excessive flooding', 'Environment', 'Flooding', 0.95),
('deep flood', 'Environment', 'Flooding', 0.95),
('minor flood', 'Environment', 'Flooding', 0.85),
('due to flood', 'Environment', 'Flooding', 0.90),
('because of flood', 'Environment', 'Flooding', 0.90),
('heavy traffic', 'Traffic Congestion', 'Traffic', 0.95),
('causing traffic', 'Traffic Congestion', 'Traffic', 0.90),
('traffic due to', 'Traffic Congestion', 'Traffic', 0.90),
('traffic because', 'Traffic Congestion', 'Traffic', 0.90),
('sirang streetlight', 'Infrastructure', 'Broken Streetlight', 0.95)
ON CONFLICT (term) DO NOTHING;

-- =================================================================
-- 3. NLP CATEGORY ANCHORS (For AI Fallback - v4.0)
-- 3-5 representative phrases per category for semantic comparison
-- =================================================================
INSERT INTO public.nlp_anchors (category, anchor_text) VALUES
-- Infrastructure
('Infrastructure', 'broken road with potholes'),
('Infrastructure', 'damaged street needs repair'),
('Infrastructure', 'guba ang kalsada dili na magamit'),
('Infrastructure', 'bridge is collapsing dangerous'),
('Infrastructure', 'sirang daan malubak napakadelikado'),
-- Utilities
('Utilities', 'no water supply for days'),
('Utilities', 'walang tubig matagal na'),
('Utilities', 'power outage blackout kuryente'),
('Utilities', 'brownout electricity problem'),
('Utilities', 'weak water pressure mahina ang tubig'),
-- Sanitation
('Sanitation', 'garbage not collected mabaho'),
('Sanitation', 'overflowing trash tambak na basura'),
('Sanitation', 'illegal dumping site marumi'),
('Sanitation', 'bad smell from sewage baho'),
('Sanitation', 'uncollected waste di nakuha basura'),
-- Environment
('Environment', 'flooding in the streets bumabaha'),
('Environment', 'flash flood dangerous water level'),
('Environment', 'baha sa aming lugar lunop'),
('Environment', 'overflow river apaw ang tubig'),
('Environment', 'landslide erosion gumuho'),
-- Public Safety
('Public Safety', 'fire emergency sunog nasusunog'),
('Public Safety', 'crime robbery holdap nakawan'),
('Public Safety', 'accident injury aksidente sugatan'),
('Public Safety', 'violence fight away barilan'),
('Public Safety', 'medical emergency patay namatay'),
-- Traffic
('Traffic Congestion', 'heavy traffic congestion trapik'),
('Traffic Congestion', 'road blocked stuck di makalusot'),
('Traffic Congestion', 'vehicle accident traffic jam'),
('Traffic Congestion', 'gridlock bottleneck siksikan'),
('Traffic Congestion', 'slow moving traffic mabagal'),
-- Stray Animals
('Stray Animals', 'stray dog attacking asong gala'),
('Stray Animals', 'dangerous animal snake ahas'),
('Stray Animals', 'rabid dog loose loko aso'),
('Stray Animals', 'wild animal in neighborhood'),
('Stray Animals', 'stray cats dogs roaming'),
-- Pests
('Pest Infestation', 'mosquito breeding dengue lamok'),
('Pest Infestation', 'rat infestation daga problema'),
('Pest Infestation', 'cockroach infestation ipis marami'),
('Pest Infestation', 'pest control needed peste'),
('Pest Infestation', 'insect problem health hazard'),
-- Noise
('Noise Complaint', 'loud karaoke noise ingay'),
('Noise Complaint', 'noisy neighbors maingay kapitbahay'),
('Noise Complaint', 'construction noise disturbance'),
('Noise Complaint', 'barking dogs all night tahol'),
('Noise Complaint', 'loud music party videoke'),
-- Others
('Others', 'general complaint concern'),
('Others', 'issue problem report'),
('Others', 'request for assistance'),
('Others', 'inquiry question concern'),
('Others', 'feedback suggestion');

-- =================================================================
-- 4. METAPHOR FILTERS (To prevent false positives)
-- =================================================================
INSERT INTO public.nlp_metaphors (pattern, literal_meaning, actual_meaning, filter_type) VALUES
('parang moon crater', 'like a moon crater', 'Describing a severe pothole', 'METAPHOR'),
('cats piss|cat''s piss', 'cat urine', 'Comparing weak water pressure', 'METAPHOR'),
('water bender', 'Avatar reference', 'Humorous reference to water control', 'GAMING_REFERENCE'),
('crystalmaiden|crystal maiden', 'Dota 2 character', 'Gaming reference', 'GAMING_REFERENCE'),
('my lambo', 'Lamborghini', 'Exaggeration about vehicle', 'HYPERBOLE'),
('hihintayin.*mamatay sa uhaw', 'wait to die of thirst', 'Rhetorical complaint about no water', 'RHETORICAL'),
('parang swimming pool', 'like a swimming pool', 'Describing a flooded area', 'METAPHOR'),
('para akong nasa impyerno', 'like in hell', 'Expressing frustration/heat', 'METAPHOR'),
('mukha ng ilog', 'looks like a river', 'Describing flooded street', 'METAPHOR'),
('parang ilog na', 'like a river now', 'Describing flooded area', 'METAPHOR'),
('parang bundok na ang basura', 'garbage like a mountain', 'Describing accumulated garbage', 'METAPHOR'),
('lungag sama sa moon crater', 'hole like moon crater', 'Describing severe pothole', 'METAPHOR'),
('daghan kaayo sama sa bukid|parang bundok', 'like a mountain', 'Describing accumulated garbage', 'METAPHOR'),
('EXTREME DANGER HOUSE FIRE HERE', 'stress test', 'False positive test', 'TEST_PATTERN'),
('URGENT FIRE EMERGENCY', 'stress test', 'False positive test', 'TEST_PATTERN'),
('flood of students|flood of people', 'flood of humans', 'Crowd', 'FIGURATIVE_FLOOD'),
('namatay ang phone|dead phone|patay ang phone', 'phone died', 'Phone battery died', 'DEVICE_METAPHOR'),
('namatay ang internet|patay ang wifi', 'internet died', 'No internet connection', 'DEVICE_METAPHOR'),
('mamamatay na ako sa init', 'dying of heat', 'Expressing discomfort', 'HYPERBOLE'),
('gutom na gutom na ako.*mamatay', 'hungry enough to die', 'Expressing hunger', 'HYPERBOLE'),
('parang dagat na|sama sa dagat', 'like an ocean', 'Describing flooded area', 'METAPHOR'),
('parang langit na|atong langit', 'like heaven', 'Expressing satisfaction', 'METAPHOR'),
('mamatay ko sa init|mamatay sa kainit', 'die of heat', 'Expressing discomfort (Bisaya)', 'HYPERBOLE'),
('patay na akong phone|namatay akong phone', 'my phone died', 'Phone battery died (Bisaya)', 'DEVICE_METAPHOR'),
('sama sa swimming pool', 'like a swimming pool (Bisaya)', 'Flooded area', 'METAPHOR')
ON CONFLICT DO NOTHING;
