// Client-side Supabase configuration
// This file will be dynamically generated by the server with proper credentials

// Global Supabase client for browser use
let supabaseClient = null;

// Function to initialize Supabase client
async function initializeSupabaseClient(url, anonKey) {
  try {
    // Check if Supabase is already loaded
    if (typeof window.supabase !== 'undefined') {
      supabaseClient = window.supabase.createClient(url, anonKey);
      console.log('Supabase client initialized');
      return supabaseClient;
    }
    
    // Load Supabase from CDN if not available
    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.39.0/dist/umd/supabase.min.js';
    script.onload = () => {
      supabaseClient = window.supabase.createClient(url, anonKey);
      console.log('Supabase loaded from CDN and initialized');
      
      // Trigger a custom event to notify that Supabase is ready
      window.dispatchEvent(new CustomEvent('supabaseReady'));
    };
    script.onerror = () => {
      console.error('Failed to load Supabase from CDN');
    };
    document.head.appendChild(script);
  } catch (error) {
    console.error('Error initializing Supabase client:', error);
  }
}

// Function to get the Supabase client
function getSupabaseClient() {
  return supabaseClient;
}

// Make functions globally available
window.initializeSupabaseClient = initializeSupabaseClient;
window.getSupabaseClient = getSupabaseClient;
